---
title: "About Central Park Squirrels"
output: github_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
library(tidyverse)
library(plotly)
library(dplyr)


knitr::opts_chunk$set(
  echo = TRUE,
  warning = FALSE,
  fig.width = 8,
  fig.height = 6,
  out.width = "90%"
  )

  options(
    ggplot2.continuous.colour = "viridis",
    ggplot2.continuous.fill = "viridis"
  )
  
  scale_colour_discrete = scale_colour_viridis_d
  scale_fill_discrete = scale_fill_viridis_d
  
  theme_set(theme_minimal() + theme(legend.position = "bottom"))
  
```


```{r wrangle_data, include=FALSE}
squirrel_data =
  read_csv("./data/squirrel_data.csv") %>% 
  janitor::clean_names()

squirrel_behavior = 
  squirrel_data %>%
  select(unique_squirrel_id, running, chasing, climbing, eating, foraging) %>%
  mutate(
    running = as.factor(running),
    chasing = as.factor(chasing),
    climbing = as.factor(climbing),
    eating = as.factor(eating),
    foraging = as.factor(foraging),
    running = 
      recode(running, "FALSE" = "no", "TRUE" = "running"),
    chasing =
      recode(chasing, "FALSE" = "no", "TRUE" = "chasing"),
    climbing =
      recode(climbing, "FALSE" = "no", "TRUE" = "climbing"),
    eating =
      recode(eating, "FALSE" = "no", "TRUE" = "eating"),
    foraging =
      recode(foraging, "FALSE" = "no", "TRUE" = "foraging")) %>%
  pivot_longer(
  running:foraging,
 names_to = "activity",
 values_to = "participation") %>%
    mutate(participation = na_if(participation, "no"))
```
## Who they are:
There were `r nrow(squirrel_data)` unique squirrels spotted in Central Park in October of 2018!

## What they look like:
Mostly gray.

```{r fur_plot, echo=FALSE}

squirrel_color = 
  squirrel_data %>%
  select(primary_fur_color) 

squirrel_color_plot = squirrel_color[!is.na(squirrel_color$primary_fur_color),] 

squirrel_color_plot <- within(squirrel_color_plot, primary_fur_color <- factor(primary_fur_color,levels = names(sort(table(primary_fur_color),decreasing = TRUE))))

squirrel_color_plot %>%
  ggplot(aes(x = primary_fur_color)) +  geom_bar(fill = "grey") + labs(title = "Primary Squirrel Fur Color", x = "Color", y = "Number of Squirrels")
```

## What they do:
Foraging is the most common observed behavior.
```{r behavior_plot, echo=FALSE}
squirrel_plot_data = squirrel_behavior[!is.na(squirrel_behavior$participation),] 

squirrel_plot_data <- within(squirrel_plot_data, participation <- factor(participation,levels = names(sort(table(participation),decreasing = TRUE))))

squirrel_plot_data %>%
ggplot(aes(x = participation)) +  geom_bar(fill = "green") + labs(title = "Common Squirrel Behaviors", x = "Behavior", y = "Number of Squirrels Exhibiting Behavior")
```

